
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Justin
 */
public class AcheterCarteDlg extends javax.swing.JDialog {

    /**
     * Creates new form AcheterCarte
     */
    public AcheterCarteDlg(java.awt.Frame parent, boolean modal, Loto l) {
        super(parent, modal);
        initComponents();
        this.l = l;
        cbJoueurs.removeAllItems();
        for (int i=0;i<l.getLstJ().getNbJoueur();i++)
            cbJoueurs.addItem((i+1)+" : "+l.getLstJ().getJoueur(i).getPseudo());
        cbJoueurs.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                refreshSolde();
            }
        });
        initPanelCarte();
    }

    private void initPanelCarte(){
        JButton btn;
        this.c = new CarteLoto(l.getNbColonne(),l.getNbNumero());
        panCarte.removeAll();
        panCarte.setLayout(new GridLayout(this.c.getLig(),this.c.getCol()));
        for (int i=0;i<this.c.getLig();i++)
            for (int j=0;j<this.c.getCol();j++){
                btn = new JButton();
                if (this.c.getTab()[i][j] != 0)
                    btn.setText(this.c.getTab()[i][j]+"");
                panCarte.add(btn);
            }
        pack();
        int n = cbJoueurs.getSelectedIndex();
        Montant.setText("Solde de "+this.l.getLstJ().getJoueur(n).getPseudo()+" : "+this.l.getLstJ().getJoueur(n).getSolde());
        this.setBounds(400, 200, 480, 360);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        lblTitre = new javax.swing.JLabel();
        panCarte = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Montant = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cbJoueurs = new javax.swing.JComboBox<>();
        AutreChoix = new javax.swing.JButton();
        Acheter = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitre.setText("Acheter une ou plusieurs cartes");
        jPanel1.add(lblTitre);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panCarte.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panCarte, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        Montant.setText("$$$");
        jPanel4.add(Montant);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        jPanel5.add(cbJoueurs);

        AutreChoix.setText("Autre choix");
        AutreChoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutreChoixActionPerformed(evt);
            }
        });
        jPanel5.add(AutreChoix);

        Acheter.setText("Acheter");
        Acheter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcheterActionPerformed(evt);
            }
        });
        jPanel5.add(Acheter);

        Quitter.setText("Quitter");
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });
        jPanel5.add(Quitter);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }
	// </editor-fold>//GEN-END:initComponents
	
	
    private void AutreChoixActionPerformed(java.awt.event.ActionEvent evt) {
        initPanelCarte();
    }
	
	
    private void AcheterActionPerformed(java.awt.event.ActionEvent evt) {
        int n = cbJoueurs.getSelectedIndex();
        l.getLstJ().getJoueur(n).acheter(c);
        Montant.setText("Solde de "+this.l.getLstJ().getJoueur(n).getPseudo()+" : "+this.l.getLstJ().getJoueur(n).getSolde());
    }

	
    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {
        this.setEnabled(false);
        this.dispose();
    }
	
    private void refreshSolde(){
        int n = cbJoueurs.getSelectedIndex();
        Montant.setText("Solde de "+this.l.getLstJ().getJoueur(n).getPseudo()+" : "+this.l.getLstJ().getJoueur(n).getSolde());
    }
        
    private Loto l;
    private CarteLoto c;

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acheter;
    private javax.swing.JButton AutreChoix;
    private javax.swing.JLabel Montant;
    private javax.swing.JButton Quitter;
    private javax.swing.JComboBox<String> cbJoueurs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JPanel panCarte;
	// End of variables declaration//GEN-END:variables
}
