
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Justin
 */
public class AjoutJoueurDlg extends javax.swing.JDialog {

    /**
     * Creates new form SaisieJoueur
     */
    public AjoutJoueurDlg(java.awt.Frame parent, boolean modal) { // constructeur de AjoutJoueurDlg
        super(parent,modal);
        initComponents(); 
        this.fin = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textPseudo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnChoisirCol = new javax.swing.JButton();
        textCouleur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSolde = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnParcourir = new javax.swing.JButton();
        photoJoueur = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAnnuler = new javax.swing.JButton();
        btnValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Pseudo");
        jPanel1.add(jLabel1);

        textPseudo.setText("Bob");
        textPseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPseudoActionPerformed(evt);
            }
        });
        jPanel1.add(textPseudo);

        jLabel2.setText("Couleur");
        jPanel1.add(jLabel2);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        btnChoisirCol.setText("Choisir Couleur");
        btnChoisirCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoisirColActionPerformed(evt);
            }
        });
        jPanel4.add(btnChoisirCol);

        textCouleur.setEditable(false);
        textCouleur.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.add(textCouleur);

        jPanel1.add(jPanel4);

        jLabel3.setText("Solde");
        jPanel1.add(jLabel3);

        btnSolde.setText("20.0€");
        jPanel1.add(btnSolde);

        jLabel6.setText("Photo");
        jPanel1.add(jLabel6);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        btnParcourir.setText("Parcourir");
        btnParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcourirActionPerformed(evt);
            }
        });
        jPanel5.add(btnParcourir);

        photoJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoJoueurActionPerformed(evt);
            }
        });
        jPanel5.add(photoJoueur);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Saisie d'un nouveau joueur");
        jPanel2.add(jLabel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnnuler);

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });
        jPanel3.add(btnValider);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPseudoActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        this.value = new Joueur( textPseudo.getText(), textCouleur.getBackground() , im); // création du joueur à ajouter
        this.fin = true;
        this.setVisible(false); // On ferme la boite de dialogue
        this.dispose();
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        this.setVisible(false); // On ferme la boite de dialogue
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnChoisirColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoisirColActionPerformed
        Color newColor = JColorChooser.showDialog(new JDialog(), "Choisis une couleur", Color.yellow);
        textCouleur.setBackground(newColor);
    }//GEN-LAST:event_btnChoisirColActionPerformed

    private void photoJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoJoueurActionPerformed
        
    }//GEN-LAST:event_photoJoueurActionPerformed

    private void btnParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcourirActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            im = new ImageIcon(fc.getSelectedFile().getAbsolutePath());
            photoJoueur.setIcon(im);
        } 
    }//GEN-LAST:event_btnParcourirActionPerformed
    
    
    public Joueur getValue(){
        return this.value;
    }
    public boolean getFin(){
        return this.fin;
    }
    
    /**
     * @param args the command line arguments
     */

    private Joueur value;
    private boolean fin;
    private ImageIcon im;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnChoisirCol;
    private javax.swing.JButton btnParcourir;
    private javax.swing.JLabel btnSolde;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton photoJoueur;
    private javax.swing.JTextField textCouleur;
    private javax.swing.JTextField textPseudo;
    // End of variables declaration//GEN-END:variables
}
