

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Justin
 */
public class VisuJoueurDlg extends javax.swing.JDialog {

    /**
     * Creates new form SaisieJoueur
     */
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal, Joueur j) { // constructeur de VisuJoueurDlg
        initComponents();
        lblPseudo.setText(j.getPseudo()); // on définit les textes et les images en fonction des informations du joueur en paramètre
        textCouleur.setEditable(false);
        textCouleur.setBackground(j.getCouleur());
        btnPhoto.setIcon(j.getPhoto());
        textInfos.setText(j.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPseudo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textCouleur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblSolde = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textInfos = new javax.swing.JTextArea();
        btnPhoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Informations relatives à un joueur");
        jPanel2.add(jLabel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setText("Fermer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Pseudo");
        jPanel4.add(jLabel1);

        lblPseudo.setText("jLabel4");
        jPanel4.add(lblPseudo);

        jLabel2.setText("Couleur");
        jPanel4.add(jLabel2);
        jPanel4.add(textCouleur);

        jLabel3.setText("Solde");
        jPanel4.add(jLabel3);

        lblSolde.setText("20.0 €");
        jPanel4.add(lblSolde);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        textInfos.setColumns(20);
        textInfos.setRows(5);
        jScrollPane1.setViewportView(textInfos);

        jPanel5.add(jScrollPane1);
        jPanel5.add(btnPhoto);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false); // on ferme la fenêtre
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPseudo;
    private javax.swing.JLabel lblSolde;
    private javax.swing.JTextField textCouleur;
    private javax.swing.JTextArea textInfos;
    // End of variables declaration//GEN-END:variables
}
